// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class WorkEntries extends Table with TableInfo<WorkEntries, WorkEntriesData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  WorkEntries(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
    'id',
    aliasedName,
    false,
    hasAutoIncrement: true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
  );
  late final GeneratedColumn<String> uid = GeneratedColumn<String>(
    'uid',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL UNIQUE',
  );
  late final GeneratedColumn<int> dateKey = GeneratedColumn<int>(
    'date_key',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> centiGongsu = GeneratedColumn<int>(
    'centi_gongsu',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> presetId = GeneratedColumn<int>(
    'preset_id',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> labelSnapshot = GeneratedColumn<String>(
    'label_snapshot',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'\'',
    defaultValue: const CustomExpression('\'\''),
  );
  late final GeneratedColumn<int> colorIdSnapshot = GeneratedColumn<int>(
    'color_id_snapshot',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<int> siteId = GeneratedColumn<int>(
    'site_id',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> unitRateWonOverride = GeneratedColumn<int>(
    'unit_rate_won_override',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> createdAtMillis = GeneratedColumn<int>(
    'created_at_millis',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> updatedAtMillis = GeneratedColumn<int>(
    'updated_at_millis',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> deletedAtMillis = GeneratedColumn<int>(
    'deleted_at_millis',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    uid,
    dateKey,
    centiGongsu,
    presetId,
    labelSnapshot,
    colorIdSnapshot,
    siteId,
    unitRateWonOverride,
    createdAtMillis,
    updatedAtMillis,
    deletedAtMillis,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'work_entries';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  WorkEntriesData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return WorkEntriesData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}id'],
      )!,
      uid: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}uid'],
      )!,
      dateKey: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}date_key'],
      )!,
      centiGongsu: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}centi_gongsu'],
      )!,
      presetId: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}preset_id'],
      ),
      labelSnapshot: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}label_snapshot'],
      )!,
      colorIdSnapshot: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}color_id_snapshot'],
      )!,
      siteId: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}site_id'],
      ),
      unitRateWonOverride: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}unit_rate_won_override'],
      ),
      createdAtMillis: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at_millis'],
      )!,
      updatedAtMillis: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}updated_at_millis'],
      )!,
      deletedAtMillis: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}deleted_at_millis'],
      ),
    );
  }

  @override
  WorkEntries createAlias(String alias) {
    return WorkEntries(attachedDatabase, alias);
  }

  @override
  bool get dontWriteConstraints => true;
}

class WorkEntriesData extends DataClass implements Insertable<WorkEntriesData> {
  final int id;
  final String uid;
  final int dateKey;
  final int centiGongsu;
  final int? presetId;
  final String labelSnapshot;
  final int colorIdSnapshot;
  final int? siteId;
  final int? unitRateWonOverride;
  final int createdAtMillis;
  final int updatedAtMillis;
  final int? deletedAtMillis;
  const WorkEntriesData({
    required this.id,
    required this.uid,
    required this.dateKey,
    required this.centiGongsu,
    this.presetId,
    required this.labelSnapshot,
    required this.colorIdSnapshot,
    this.siteId,
    this.unitRateWonOverride,
    required this.createdAtMillis,
    required this.updatedAtMillis,
    this.deletedAtMillis,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['uid'] = Variable<String>(uid);
    map['date_key'] = Variable<int>(dateKey);
    map['centi_gongsu'] = Variable<int>(centiGongsu);
    if (!nullToAbsent || presetId != null) {
      map['preset_id'] = Variable<int>(presetId);
    }
    map['label_snapshot'] = Variable<String>(labelSnapshot);
    map['color_id_snapshot'] = Variable<int>(colorIdSnapshot);
    if (!nullToAbsent || siteId != null) {
      map['site_id'] = Variable<int>(siteId);
    }
    if (!nullToAbsent || unitRateWonOverride != null) {
      map['unit_rate_won_override'] = Variable<int>(unitRateWonOverride);
    }
    map['created_at_millis'] = Variable<int>(createdAtMillis);
    map['updated_at_millis'] = Variable<int>(updatedAtMillis);
    if (!nullToAbsent || deletedAtMillis != null) {
      map['deleted_at_millis'] = Variable<int>(deletedAtMillis);
    }
    return map;
  }

  WorkEntriesCompanion toCompanion(bool nullToAbsent) {
    return WorkEntriesCompanion(
      id: Value(id),
      uid: Value(uid),
      dateKey: Value(dateKey),
      centiGongsu: Value(centiGongsu),
      presetId: presetId == null && nullToAbsent
          ? const Value.absent()
          : Value(presetId),
      labelSnapshot: Value(labelSnapshot),
      colorIdSnapshot: Value(colorIdSnapshot),
      siteId: siteId == null && nullToAbsent
          ? const Value.absent()
          : Value(siteId),
      unitRateWonOverride: unitRateWonOverride == null && nullToAbsent
          ? const Value.absent()
          : Value(unitRateWonOverride),
      createdAtMillis: Value(createdAtMillis),
      updatedAtMillis: Value(updatedAtMillis),
      deletedAtMillis: deletedAtMillis == null && nullToAbsent
          ? const Value.absent()
          : Value(deletedAtMillis),
    );
  }

  factory WorkEntriesData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return WorkEntriesData(
      id: serializer.fromJson<int>(json['id']),
      uid: serializer.fromJson<String>(json['uid']),
      dateKey: serializer.fromJson<int>(json['dateKey']),
      centiGongsu: serializer.fromJson<int>(json['centiGongsu']),
      presetId: serializer.fromJson<int?>(json['presetId']),
      labelSnapshot: serializer.fromJson<String>(json['labelSnapshot']),
      colorIdSnapshot: serializer.fromJson<int>(json['colorIdSnapshot']),
      siteId: serializer.fromJson<int?>(json['siteId']),
      unitRateWonOverride: serializer.fromJson<int?>(
        json['unitRateWonOverride'],
      ),
      createdAtMillis: serializer.fromJson<int>(json['createdAtMillis']),
      updatedAtMillis: serializer.fromJson<int>(json['updatedAtMillis']),
      deletedAtMillis: serializer.fromJson<int?>(json['deletedAtMillis']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'uid': serializer.toJson<String>(uid),
      'dateKey': serializer.toJson<int>(dateKey),
      'centiGongsu': serializer.toJson<int>(centiGongsu),
      'presetId': serializer.toJson<int?>(presetId),
      'labelSnapshot': serializer.toJson<String>(labelSnapshot),
      'colorIdSnapshot': serializer.toJson<int>(colorIdSnapshot),
      'siteId': serializer.toJson<int?>(siteId),
      'unitRateWonOverride': serializer.toJson<int?>(unitRateWonOverride),
      'createdAtMillis': serializer.toJson<int>(createdAtMillis),
      'updatedAtMillis': serializer.toJson<int>(updatedAtMillis),
      'deletedAtMillis': serializer.toJson<int?>(deletedAtMillis),
    };
  }

  WorkEntriesData copyWith({
    int? id,
    String? uid,
    int? dateKey,
    int? centiGongsu,
    Value<int?> presetId = const Value.absent(),
    String? labelSnapshot,
    int? colorIdSnapshot,
    Value<int?> siteId = const Value.absent(),
    Value<int?> unitRateWonOverride = const Value.absent(),
    int? createdAtMillis,
    int? updatedAtMillis,
    Value<int?> deletedAtMillis = const Value.absent(),
  }) => WorkEntriesData(
    id: id ?? this.id,
    uid: uid ?? this.uid,
    dateKey: dateKey ?? this.dateKey,
    centiGongsu: centiGongsu ?? this.centiGongsu,
    presetId: presetId.present ? presetId.value : this.presetId,
    labelSnapshot: labelSnapshot ?? this.labelSnapshot,
    colorIdSnapshot: colorIdSnapshot ?? this.colorIdSnapshot,
    siteId: siteId.present ? siteId.value : this.siteId,
    unitRateWonOverride: unitRateWonOverride.present
        ? unitRateWonOverride.value
        : this.unitRateWonOverride,
    createdAtMillis: createdAtMillis ?? this.createdAtMillis,
    updatedAtMillis: updatedAtMillis ?? this.updatedAtMillis,
    deletedAtMillis: deletedAtMillis.present
        ? deletedAtMillis.value
        : this.deletedAtMillis,
  );
  WorkEntriesData copyWithCompanion(WorkEntriesCompanion data) {
    return WorkEntriesData(
      id: data.id.present ? data.id.value : this.id,
      uid: data.uid.present ? data.uid.value : this.uid,
      dateKey: data.dateKey.present ? data.dateKey.value : this.dateKey,
      centiGongsu: data.centiGongsu.present
          ? data.centiGongsu.value
          : this.centiGongsu,
      presetId: data.presetId.present ? data.presetId.value : this.presetId,
      labelSnapshot: data.labelSnapshot.present
          ? data.labelSnapshot.value
          : this.labelSnapshot,
      colorIdSnapshot: data.colorIdSnapshot.present
          ? data.colorIdSnapshot.value
          : this.colorIdSnapshot,
      siteId: data.siteId.present ? data.siteId.value : this.siteId,
      unitRateWonOverride: data.unitRateWonOverride.present
          ? data.unitRateWonOverride.value
          : this.unitRateWonOverride,
      createdAtMillis: data.createdAtMillis.present
          ? data.createdAtMillis.value
          : this.createdAtMillis,
      updatedAtMillis: data.updatedAtMillis.present
          ? data.updatedAtMillis.value
          : this.updatedAtMillis,
      deletedAtMillis: data.deletedAtMillis.present
          ? data.deletedAtMillis.value
          : this.deletedAtMillis,
    );
  }

  @override
  String toString() {
    return (StringBuffer('WorkEntriesData(')
          ..write('id: $id, ')
          ..write('uid: $uid, ')
          ..write('dateKey: $dateKey, ')
          ..write('centiGongsu: $centiGongsu, ')
          ..write('presetId: $presetId, ')
          ..write('labelSnapshot: $labelSnapshot, ')
          ..write('colorIdSnapshot: $colorIdSnapshot, ')
          ..write('siteId: $siteId, ')
          ..write('unitRateWonOverride: $unitRateWonOverride, ')
          ..write('createdAtMillis: $createdAtMillis, ')
          ..write('updatedAtMillis: $updatedAtMillis, ')
          ..write('deletedAtMillis: $deletedAtMillis')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    uid,
    dateKey,
    centiGongsu,
    presetId,
    labelSnapshot,
    colorIdSnapshot,
    siteId,
    unitRateWonOverride,
    createdAtMillis,
    updatedAtMillis,
    deletedAtMillis,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is WorkEntriesData &&
          other.id == this.id &&
          other.uid == this.uid &&
          other.dateKey == this.dateKey &&
          other.centiGongsu == this.centiGongsu &&
          other.presetId == this.presetId &&
          other.labelSnapshot == this.labelSnapshot &&
          other.colorIdSnapshot == this.colorIdSnapshot &&
          other.siteId == this.siteId &&
          other.unitRateWonOverride == this.unitRateWonOverride &&
          other.createdAtMillis == this.createdAtMillis &&
          other.updatedAtMillis == this.updatedAtMillis &&
          other.deletedAtMillis == this.deletedAtMillis);
}

class WorkEntriesCompanion extends UpdateCompanion<WorkEntriesData> {
  final Value<int> id;
  final Value<String> uid;
  final Value<int> dateKey;
  final Value<int> centiGongsu;
  final Value<int?> presetId;
  final Value<String> labelSnapshot;
  final Value<int> colorIdSnapshot;
  final Value<int?> siteId;
  final Value<int?> unitRateWonOverride;
  final Value<int> createdAtMillis;
  final Value<int> updatedAtMillis;
  final Value<int?> deletedAtMillis;
  const WorkEntriesCompanion({
    this.id = const Value.absent(),
    this.uid = const Value.absent(),
    this.dateKey = const Value.absent(),
    this.centiGongsu = const Value.absent(),
    this.presetId = const Value.absent(),
    this.labelSnapshot = const Value.absent(),
    this.colorIdSnapshot = const Value.absent(),
    this.siteId = const Value.absent(),
    this.unitRateWonOverride = const Value.absent(),
    this.createdAtMillis = const Value.absent(),
    this.updatedAtMillis = const Value.absent(),
    this.deletedAtMillis = const Value.absent(),
  });
  WorkEntriesCompanion.insert({
    this.id = const Value.absent(),
    required String uid,
    required int dateKey,
    required int centiGongsu,
    this.presetId = const Value.absent(),
    this.labelSnapshot = const Value.absent(),
    this.colorIdSnapshot = const Value.absent(),
    this.siteId = const Value.absent(),
    this.unitRateWonOverride = const Value.absent(),
    required int createdAtMillis,
    required int updatedAtMillis,
    this.deletedAtMillis = const Value.absent(),
  }) : uid = Value(uid),
       dateKey = Value(dateKey),
       centiGongsu = Value(centiGongsu),
       createdAtMillis = Value(createdAtMillis),
       updatedAtMillis = Value(updatedAtMillis);
  static Insertable<WorkEntriesData> custom({
    Expression<int>? id,
    Expression<String>? uid,
    Expression<int>? dateKey,
    Expression<int>? centiGongsu,
    Expression<int>? presetId,
    Expression<String>? labelSnapshot,
    Expression<int>? colorIdSnapshot,
    Expression<int>? siteId,
    Expression<int>? unitRateWonOverride,
    Expression<int>? createdAtMillis,
    Expression<int>? updatedAtMillis,
    Expression<int>? deletedAtMillis,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (uid != null) 'uid': uid,
      if (dateKey != null) 'date_key': dateKey,
      if (centiGongsu != null) 'centi_gongsu': centiGongsu,
      if (presetId != null) 'preset_id': presetId,
      if (labelSnapshot != null) 'label_snapshot': labelSnapshot,
      if (colorIdSnapshot != null) 'color_id_snapshot': colorIdSnapshot,
      if (siteId != null) 'site_id': siteId,
      if (unitRateWonOverride != null)
        'unit_rate_won_override': unitRateWonOverride,
      if (createdAtMillis != null) 'created_at_millis': createdAtMillis,
      if (updatedAtMillis != null) 'updated_at_millis': updatedAtMillis,
      if (deletedAtMillis != null) 'deleted_at_millis': deletedAtMillis,
    });
  }

  WorkEntriesCompanion copyWith({
    Value<int>? id,
    Value<String>? uid,
    Value<int>? dateKey,
    Value<int>? centiGongsu,
    Value<int?>? presetId,
    Value<String>? labelSnapshot,
    Value<int>? colorIdSnapshot,
    Value<int?>? siteId,
    Value<int?>? unitRateWonOverride,
    Value<int>? createdAtMillis,
    Value<int>? updatedAtMillis,
    Value<int?>? deletedAtMillis,
  }) {
    return WorkEntriesCompanion(
      id: id ?? this.id,
      uid: uid ?? this.uid,
      dateKey: dateKey ?? this.dateKey,
      centiGongsu: centiGongsu ?? this.centiGongsu,
      presetId: presetId ?? this.presetId,
      labelSnapshot: labelSnapshot ?? this.labelSnapshot,
      colorIdSnapshot: colorIdSnapshot ?? this.colorIdSnapshot,
      siteId: siteId ?? this.siteId,
      unitRateWonOverride: unitRateWonOverride ?? this.unitRateWonOverride,
      createdAtMillis: createdAtMillis ?? this.createdAtMillis,
      updatedAtMillis: updatedAtMillis ?? this.updatedAtMillis,
      deletedAtMillis: deletedAtMillis ?? this.deletedAtMillis,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<int>(id.value);
    }
    if (uid.present) {
      map['uid'] = Variable<String>(uid.value);
    }
    if (dateKey.present) {
      map['date_key'] = Variable<int>(dateKey.value);
    }
    if (centiGongsu.present) {
      map['centi_gongsu'] = Variable<int>(centiGongsu.value);
    }
    if (presetId.present) {
      map['preset_id'] = Variable<int>(presetId.value);
    }
    if (labelSnapshot.present) {
      map['label_snapshot'] = Variable<String>(labelSnapshot.value);
    }
    if (colorIdSnapshot.present) {
      map['color_id_snapshot'] = Variable<int>(colorIdSnapshot.value);
    }
    if (siteId.present) {
      map['site_id'] = Variable<int>(siteId.value);
    }
    if (unitRateWonOverride.present) {
      map['unit_rate_won_override'] = Variable<int>(unitRateWonOverride.value);
    }
    if (createdAtMillis.present) {
      map['created_at_millis'] = Variable<int>(createdAtMillis.value);
    }
    if (updatedAtMillis.present) {
      map['updated_at_millis'] = Variable<int>(updatedAtMillis.value);
    }
    if (deletedAtMillis.present) {
      map['deleted_at_millis'] = Variable<int>(deletedAtMillis.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('WorkEntriesCompanion(')
          ..write('id: $id, ')
          ..write('uid: $uid, ')
          ..write('dateKey: $dateKey, ')
          ..write('centiGongsu: $centiGongsu, ')
          ..write('presetId: $presetId, ')
          ..write('labelSnapshot: $labelSnapshot, ')
          ..write('colorIdSnapshot: $colorIdSnapshot, ')
          ..write('siteId: $siteId, ')
          ..write('unitRateWonOverride: $unitRateWonOverride, ')
          ..write('createdAtMillis: $createdAtMillis, ')
          ..write('updatedAtMillis: $updatedAtMillis, ')
          ..write('deletedAtMillis: $deletedAtMillis')
          ..write(')'))
        .toString();
  }
}

class Presets extends Table with TableInfo<Presets, PresetsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Presets(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
    'id',
    aliasedName,
    false,
    hasAutoIncrement: true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
  );
  late final GeneratedColumn<String> uid = GeneratedColumn<String>(
    'uid',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL UNIQUE',
  );
  late final GeneratedColumn<String> name = GeneratedColumn<String>(
    'name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> centiGongsu = GeneratedColumn<int>(
    'centi_gongsu',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> colorId = GeneratedColumn<int>(
    'color_id',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<int> sortOrder = GeneratedColumn<int>(
    'sort_order',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> isArchived = GeneratedColumn<int>(
    'is_archived',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_archived IN (0, 1))',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<int> createdAtMillis = GeneratedColumn<int>(
    'created_at_millis',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> updatedAtMillis = GeneratedColumn<int>(
    'updated_at_millis',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    uid,
    name,
    centiGongsu,
    colorId,
    sortOrder,
    isArchived,
    createdAtMillis,
    updatedAtMillis,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'presets';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  PresetsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return PresetsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}id'],
      )!,
      uid: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}uid'],
      )!,
      name: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}name'],
      )!,
      centiGongsu: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}centi_gongsu'],
      )!,
      colorId: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}color_id'],
      )!,
      sortOrder: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}sort_order'],
      )!,
      isArchived: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}is_archived'],
      )!,
      createdAtMillis: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at_millis'],
      )!,
      updatedAtMillis: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}updated_at_millis'],
      )!,
    );
  }

  @override
  Presets createAlias(String alias) {
    return Presets(attachedDatabase, alias);
  }

  @override
  bool get dontWriteConstraints => true;
}

class PresetsData extends DataClass implements Insertable<PresetsData> {
  final int id;
  final String uid;
  final String name;
  final int centiGongsu;
  final int colorId;
  final int sortOrder;
  final int isArchived;
  final int createdAtMillis;
  final int updatedAtMillis;
  const PresetsData({
    required this.id,
    required this.uid,
    required this.name,
    required this.centiGongsu,
    required this.colorId,
    required this.sortOrder,
    required this.isArchived,
    required this.createdAtMillis,
    required this.updatedAtMillis,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['uid'] = Variable<String>(uid);
    map['name'] = Variable<String>(name);
    map['centi_gongsu'] = Variable<int>(centiGongsu);
    map['color_id'] = Variable<int>(colorId);
    map['sort_order'] = Variable<int>(sortOrder);
    map['is_archived'] = Variable<int>(isArchived);
    map['created_at_millis'] = Variable<int>(createdAtMillis);
    map['updated_at_millis'] = Variable<int>(updatedAtMillis);
    return map;
  }

  PresetsCompanion toCompanion(bool nullToAbsent) {
    return PresetsCompanion(
      id: Value(id),
      uid: Value(uid),
      name: Value(name),
      centiGongsu: Value(centiGongsu),
      colorId: Value(colorId),
      sortOrder: Value(sortOrder),
      isArchived: Value(isArchived),
      createdAtMillis: Value(createdAtMillis),
      updatedAtMillis: Value(updatedAtMillis),
    );
  }

  factory PresetsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return PresetsData(
      id: serializer.fromJson<int>(json['id']),
      uid: serializer.fromJson<String>(json['uid']),
      name: serializer.fromJson<String>(json['name']),
      centiGongsu: serializer.fromJson<int>(json['centiGongsu']),
      colorId: serializer.fromJson<int>(json['colorId']),
      sortOrder: serializer.fromJson<int>(json['sortOrder']),
      isArchived: serializer.fromJson<int>(json['isArchived']),
      createdAtMillis: serializer.fromJson<int>(json['createdAtMillis']),
      updatedAtMillis: serializer.fromJson<int>(json['updatedAtMillis']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'uid': serializer.toJson<String>(uid),
      'name': serializer.toJson<String>(name),
      'centiGongsu': serializer.toJson<int>(centiGongsu),
      'colorId': serializer.toJson<int>(colorId),
      'sortOrder': serializer.toJson<int>(sortOrder),
      'isArchived': serializer.toJson<int>(isArchived),
      'createdAtMillis': serializer.toJson<int>(createdAtMillis),
      'updatedAtMillis': serializer.toJson<int>(updatedAtMillis),
    };
  }

  PresetsData copyWith({
    int? id,
    String? uid,
    String? name,
    int? centiGongsu,
    int? colorId,
    int? sortOrder,
    int? isArchived,
    int? createdAtMillis,
    int? updatedAtMillis,
  }) => PresetsData(
    id: id ?? this.id,
    uid: uid ?? this.uid,
    name: name ?? this.name,
    centiGongsu: centiGongsu ?? this.centiGongsu,
    colorId: colorId ?? this.colorId,
    sortOrder: sortOrder ?? this.sortOrder,
    isArchived: isArchived ?? this.isArchived,
    createdAtMillis: createdAtMillis ?? this.createdAtMillis,
    updatedAtMillis: updatedAtMillis ?? this.updatedAtMillis,
  );
  PresetsData copyWithCompanion(PresetsCompanion data) {
    return PresetsData(
      id: data.id.present ? data.id.value : this.id,
      uid: data.uid.present ? data.uid.value : this.uid,
      name: data.name.present ? data.name.value : this.name,
      centiGongsu: data.centiGongsu.present
          ? data.centiGongsu.value
          : this.centiGongsu,
      colorId: data.colorId.present ? data.colorId.value : this.colorId,
      sortOrder: data.sortOrder.present ? data.sortOrder.value : this.sortOrder,
      isArchived: data.isArchived.present
          ? data.isArchived.value
          : this.isArchived,
      createdAtMillis: data.createdAtMillis.present
          ? data.createdAtMillis.value
          : this.createdAtMillis,
      updatedAtMillis: data.updatedAtMillis.present
          ? data.updatedAtMillis.value
          : this.updatedAtMillis,
    );
  }

  @override
  String toString() {
    return (StringBuffer('PresetsData(')
          ..write('id: $id, ')
          ..write('uid: $uid, ')
          ..write('name: $name, ')
          ..write('centiGongsu: $centiGongsu, ')
          ..write('colorId: $colorId, ')
          ..write('sortOrder: $sortOrder, ')
          ..write('isArchived: $isArchived, ')
          ..write('createdAtMillis: $createdAtMillis, ')
          ..write('updatedAtMillis: $updatedAtMillis')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    uid,
    name,
    centiGongsu,
    colorId,
    sortOrder,
    isArchived,
    createdAtMillis,
    updatedAtMillis,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is PresetsData &&
          other.id == this.id &&
          other.uid == this.uid &&
          other.name == this.name &&
          other.centiGongsu == this.centiGongsu &&
          other.colorId == this.colorId &&
          other.sortOrder == this.sortOrder &&
          other.isArchived == this.isArchived &&
          other.createdAtMillis == this.createdAtMillis &&
          other.updatedAtMillis == this.updatedAtMillis);
}

class PresetsCompanion extends UpdateCompanion<PresetsData> {
  final Value<int> id;
  final Value<String> uid;
  final Value<String> name;
  final Value<int> centiGongsu;
  final Value<int> colorId;
  final Value<int> sortOrder;
  final Value<int> isArchived;
  final Value<int> createdAtMillis;
  final Value<int> updatedAtMillis;
  const PresetsCompanion({
    this.id = const Value.absent(),
    this.uid = const Value.absent(),
    this.name = const Value.absent(),
    this.centiGongsu = const Value.absent(),
    this.colorId = const Value.absent(),
    this.sortOrder = const Value.absent(),
    this.isArchived = const Value.absent(),
    this.createdAtMillis = const Value.absent(),
    this.updatedAtMillis = const Value.absent(),
  });
  PresetsCompanion.insert({
    this.id = const Value.absent(),
    required String uid,
    required String name,
    required int centiGongsu,
    this.colorId = const Value.absent(),
    required int sortOrder,
    this.isArchived = const Value.absent(),
    required int createdAtMillis,
    required int updatedAtMillis,
  }) : uid = Value(uid),
       name = Value(name),
       centiGongsu = Value(centiGongsu),
       sortOrder = Value(sortOrder),
       createdAtMillis = Value(createdAtMillis),
       updatedAtMillis = Value(updatedAtMillis);
  static Insertable<PresetsData> custom({
    Expression<int>? id,
    Expression<String>? uid,
    Expression<String>? name,
    Expression<int>? centiGongsu,
    Expression<int>? colorId,
    Expression<int>? sortOrder,
    Expression<int>? isArchived,
    Expression<int>? createdAtMillis,
    Expression<int>? updatedAtMillis,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (uid != null) 'uid': uid,
      if (name != null) 'name': name,
      if (centiGongsu != null) 'centi_gongsu': centiGongsu,
      if (colorId != null) 'color_id': colorId,
      if (sortOrder != null) 'sort_order': sortOrder,
      if (isArchived != null) 'is_archived': isArchived,
      if (createdAtMillis != null) 'created_at_millis': createdAtMillis,
      if (updatedAtMillis != null) 'updated_at_millis': updatedAtMillis,
    });
  }

  PresetsCompanion copyWith({
    Value<int>? id,
    Value<String>? uid,
    Value<String>? name,
    Value<int>? centiGongsu,
    Value<int>? colorId,
    Value<int>? sortOrder,
    Value<int>? isArchived,
    Value<int>? createdAtMillis,
    Value<int>? updatedAtMillis,
  }) {
    return PresetsCompanion(
      id: id ?? this.id,
      uid: uid ?? this.uid,
      name: name ?? this.name,
      centiGongsu: centiGongsu ?? this.centiGongsu,
      colorId: colorId ?? this.colorId,
      sortOrder: sortOrder ?? this.sortOrder,
      isArchived: isArchived ?? this.isArchived,
      createdAtMillis: createdAtMillis ?? this.createdAtMillis,
      updatedAtMillis: updatedAtMillis ?? this.updatedAtMillis,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<int>(id.value);
    }
    if (uid.present) {
      map['uid'] = Variable<String>(uid.value);
    }
    if (name.present) {
      map['name'] = Variable<String>(name.value);
    }
    if (centiGongsu.present) {
      map['centi_gongsu'] = Variable<int>(centiGongsu.value);
    }
    if (colorId.present) {
      map['color_id'] = Variable<int>(colorId.value);
    }
    if (sortOrder.present) {
      map['sort_order'] = Variable<int>(sortOrder.value);
    }
    if (isArchived.present) {
      map['is_archived'] = Variable<int>(isArchived.value);
    }
    if (createdAtMillis.present) {
      map['created_at_millis'] = Variable<int>(createdAtMillis.value);
    }
    if (updatedAtMillis.present) {
      map['updated_at_millis'] = Variable<int>(updatedAtMillis.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('PresetsCompanion(')
          ..write('id: $id, ')
          ..write('uid: $uid, ')
          ..write('name: $name, ')
          ..write('centiGongsu: $centiGongsu, ')
          ..write('colorId: $colorId, ')
          ..write('sortOrder: $sortOrder, ')
          ..write('isArchived: $isArchived, ')
          ..write('createdAtMillis: $createdAtMillis, ')
          ..write('updatedAtMillis: $updatedAtMillis')
          ..write(')'))
        .toString();
  }
}

class DayMemos extends Table with TableInfo<DayMemos, DayMemosData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DayMemos(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> dateKey = GeneratedColumn<int>(
    'date_key',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> body = GeneratedColumn<String>(
    'body',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> updatedAtMillis = GeneratedColumn<int>(
    'updated_at_millis',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [dateKey, body, updatedAtMillis];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'day_memos';
  @override
  Set<GeneratedColumn> get $primaryKey => {dateKey};
  @override
  DayMemosData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return DayMemosData(
      dateKey: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}date_key'],
      )!,
      body: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}body'],
      )!,
      updatedAtMillis: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}updated_at_millis'],
      )!,
    );
  }

  @override
  DayMemos createAlias(String alias) {
    return DayMemos(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(date_key)'];
  @override
  bool get dontWriteConstraints => true;
}

class DayMemosData extends DataClass implements Insertable<DayMemosData> {
  final int dateKey;
  final String body;
  final int updatedAtMillis;
  const DayMemosData({
    required this.dateKey,
    required this.body,
    required this.updatedAtMillis,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['date_key'] = Variable<int>(dateKey);
    map['body'] = Variable<String>(body);
    map['updated_at_millis'] = Variable<int>(updatedAtMillis);
    return map;
  }

  DayMemosCompanion toCompanion(bool nullToAbsent) {
    return DayMemosCompanion(
      dateKey: Value(dateKey),
      body: Value(body),
      updatedAtMillis: Value(updatedAtMillis),
    );
  }

  factory DayMemosData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return DayMemosData(
      dateKey: serializer.fromJson<int>(json['dateKey']),
      body: serializer.fromJson<String>(json['body']),
      updatedAtMillis: serializer.fromJson<int>(json['updatedAtMillis']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'dateKey': serializer.toJson<int>(dateKey),
      'body': serializer.toJson<String>(body),
      'updatedAtMillis': serializer.toJson<int>(updatedAtMillis),
    };
  }

  DayMemosData copyWith({int? dateKey, String? body, int? updatedAtMillis}) =>
      DayMemosData(
        dateKey: dateKey ?? this.dateKey,
        body: body ?? this.body,
        updatedAtMillis: updatedAtMillis ?? this.updatedAtMillis,
      );
  DayMemosData copyWithCompanion(DayMemosCompanion data) {
    return DayMemosData(
      dateKey: data.dateKey.present ? data.dateKey.value : this.dateKey,
      body: data.body.present ? data.body.value : this.body,
      updatedAtMillis: data.updatedAtMillis.present
          ? data.updatedAtMillis.value
          : this.updatedAtMillis,
    );
  }

  @override
  String toString() {
    return (StringBuffer('DayMemosData(')
          ..write('dateKey: $dateKey, ')
          ..write('body: $body, ')
          ..write('updatedAtMillis: $updatedAtMillis')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(dateKey, body, updatedAtMillis);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is DayMemosData &&
          other.dateKey == this.dateKey &&
          other.body == this.body &&
          other.updatedAtMillis == this.updatedAtMillis);
}

class DayMemosCompanion extends UpdateCompanion<DayMemosData> {
  final Value<int> dateKey;
  final Value<String> body;
  final Value<int> updatedAtMillis;
  const DayMemosCompanion({
    this.dateKey = const Value.absent(),
    this.body = const Value.absent(),
    this.updatedAtMillis = const Value.absent(),
  });
  DayMemosCompanion.insert({
    this.dateKey = const Value.absent(),
    required String body,
    required int updatedAtMillis,
  }) : body = Value(body),
       updatedAtMillis = Value(updatedAtMillis);
  static Insertable<DayMemosData> custom({
    Expression<int>? dateKey,
    Expression<String>? body,
    Expression<int>? updatedAtMillis,
  }) {
    return RawValuesInsertable({
      if (dateKey != null) 'date_key': dateKey,
      if (body != null) 'body': body,
      if (updatedAtMillis != null) 'updated_at_millis': updatedAtMillis,
    });
  }

  DayMemosCompanion copyWith({
    Value<int>? dateKey,
    Value<String>? body,
    Value<int>? updatedAtMillis,
  }) {
    return DayMemosCompanion(
      dateKey: dateKey ?? this.dateKey,
      body: body ?? this.body,
      updatedAtMillis: updatedAtMillis ?? this.updatedAtMillis,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (dateKey.present) {
      map['date_key'] = Variable<int>(dateKey.value);
    }
    if (body.present) {
      map['body'] = Variable<String>(body.value);
    }
    if (updatedAtMillis.present) {
      map['updated_at_millis'] = Variable<int>(updatedAtMillis.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('DayMemosCompanion(')
          ..write('dateKey: $dateKey, ')
          ..write('body: $body, ')
          ..write('updatedAtMillis: $updatedAtMillis')
          ..write(')'))
        .toString();
  }
}

class AppSettings extends Table with TableInfo<AppSettings, AppSettingsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  AppSettings(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> key = GeneratedColumn<String>(
    'key',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> value = GeneratedColumn<String>(
    'value',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [key, value];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'app_settings';
  @override
  Set<GeneratedColumn> get $primaryKey => {key};
  @override
  AppSettingsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return AppSettingsData(
      key: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}key'],
      )!,
      value: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}value'],
      )!,
    );
  }

  @override
  AppSettings createAlias(String alias) {
    return AppSettings(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY("key")'];
  @override
  bool get dontWriteConstraints => true;
}

class AppSettingsData extends DataClass implements Insertable<AppSettingsData> {
  final String key;
  final String value;
  const AppSettingsData({required this.key, required this.value});
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['key'] = Variable<String>(key);
    map['value'] = Variable<String>(value);
    return map;
  }

  AppSettingsCompanion toCompanion(bool nullToAbsent) {
    return AppSettingsCompanion(key: Value(key), value: Value(value));
  }

  factory AppSettingsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return AppSettingsData(
      key: serializer.fromJson<String>(json['key']),
      value: serializer.fromJson<String>(json['value']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'key': serializer.toJson<String>(key),
      'value': serializer.toJson<String>(value),
    };
  }

  AppSettingsData copyWith({String? key, String? value}) =>
      AppSettingsData(key: key ?? this.key, value: value ?? this.value);
  AppSettingsData copyWithCompanion(AppSettingsCompanion data) {
    return AppSettingsData(
      key: data.key.present ? data.key.value : this.key,
      value: data.value.present ? data.value.value : this.value,
    );
  }

  @override
  String toString() {
    return (StringBuffer('AppSettingsData(')
          ..write('key: $key, ')
          ..write('value: $value')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(key, value);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is AppSettingsData &&
          other.key == this.key &&
          other.value == this.value);
}

class AppSettingsCompanion extends UpdateCompanion<AppSettingsData> {
  final Value<String> key;
  final Value<String> value;
  final Value<int> rowid;
  const AppSettingsCompanion({
    this.key = const Value.absent(),
    this.value = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  AppSettingsCompanion.insert({
    required String key,
    required String value,
    this.rowid = const Value.absent(),
  }) : key = Value(key),
       value = Value(value);
  static Insertable<AppSettingsData> custom({
    Expression<String>? key,
    Expression<String>? value,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (key != null) 'key': key,
      if (value != null) 'value': value,
      if (rowid != null) 'rowid': rowid,
    });
  }

  AppSettingsCompanion copyWith({
    Value<String>? key,
    Value<String>? value,
    Value<int>? rowid,
  }) {
    return AppSettingsCompanion(
      key: key ?? this.key,
      value: value ?? this.value,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (key.present) {
      map['key'] = Variable<String>(key.value);
    }
    if (value.present) {
      map['value'] = Variable<String>(value.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('AppSettingsCompanion(')
          ..write('key: $key, ')
          ..write('value: $value, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class DatabaseAtV1 extends GeneratedDatabase {
  DatabaseAtV1(QueryExecutor e) : super(e);
  late final WorkEntries workEntries = WorkEntries(this);
  late final Presets presets = Presets(this);
  late final DayMemos dayMemos = DayMemos(this);
  late final AppSettings appSettings = AppSettings(this);
  late final Index idxWorkEntriesDate = Index(
    'idx_work_entries_date',
    'CREATE INDEX idx_work_entries_date ON work_entries (date_key)',
  );
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
    workEntries,
    presets,
    dayMemos,
    appSettings,
    idxWorkEntriesDate,
  ];
  @override
  int get schemaVersion => 1;
}
